### PR TITLE
build: fix npm version of "mongodb-backup" and "mongodb-restore"

### PR DESCRIPTION
**Pull request by hex7c0**
the previous version is releated to `1.0.2` on github repo
stream option is available since `1.1.0` version

latest version is released with iojs@3 test

### CODE REVIEW

**Comment by IstoraMandiri** [comment]
Thanks for all your work @hex7c0!

**Comment by IstoraMandiri** [comment]
Will most likely be able to do a new release tomorrow.

**Comment by hex7c0** [comment]
you're welcome

p.s.
there is a typo inside README
https://github.com/hitchcott/app-dump#metoer-app-dump -> `meteor`
#grammarnazi

**Comment by IstoraMandiri** [comment]
Thanks! I'll correct that too.

BTW, I just tried your fork and I'm getting whenever an error when I try to restore. Looks like `drop` isn't working properly.

```
I20150904-11:27:12.956(8)? Error in oplog callback Error: insert found for already-existing ID in published
I20150904-11:27:12.958(8)?     at packages/mongo/oplog_observe_driver.js:562:1
I20150904-11:27:12.959(8)?     at Object.Meteor._noYieldsAllowed (packages/meteor/fiber_helpers.js:11:1)
I20150904-11:27:12.959(8)?     at [object Object]._.extend._handleOplogEntrySteadyOrFetching (packages/mongo/oplog_observe_driver.js:545:1)
I20150904-11:27:12.959(8)?     at packages/mongo/oplog_observe_driver.js:118:1
I20150904-11:27:12.959(8)?     at packages/mongo/oplog_observe_driver.js:16:1
I20150904-11:27:12.959(8)?     at Object.Meteor._noYieldsAllowed (packages/meteor/fiber_helpers.js:11:1)
I20150904-11:27:12.959(8)?     at packages/mongo/oplog_observe_driver.js:106:1
I20150904-11:27:12.959(8)?     at packages/mongo/oplog_tailing.js:79:1
I20150904-11:27:12.959(8)?     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108:1)
I20150904-11:27:12.959(8)?     at packages/meteor/dynamics_nodejs.js:121:1
```

I think this is the same reason I was using a forked version of your package; I was manually dropping to prevent that. See https://github.com/hitchcott/mongodb-restore/commit/2e02c754689143f023dc8ec4c4eebbe86f5d7df4

I think this is a [meteor compatibility](https://github.com/meteor/meteor/issues/3847) issue; can we add this as an option in `mongodb-restore` ?

**Comment by hex7c0** [comment]
mmm, I'm working on it

**Comment by hex7c0** [comment]
now you can use `dropCollections: true` for simulate `drop: true` option

I'll release this version tonight
UTC timezone

**Comment by hex7c0** [comment]
hey @hitchcott, try `1.4.0` version

with `dropCollections: true`
https://github.com/hex7c0/mongodb-restore/blob/master/examples/dropCollections.js#L22

**Comment by hex7c0** [comment]
have you tried updated versions?

**Comment by IstoraMandiri** [comment]
Hi @hex7c0 , sorry I haven't had chance to implement this yet but today is Open Source Friday so let's see what happens ;) 

opening an issue for it...

**Comment by hex7c0** [comment]
:+1:

**Pull request merged**
